trigger:
- none

pr:
- master

variables:
- group: ZULIP_VAR_GROUP

jobs:
- job: publish
  timeoutInMinutes: 60
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # Trigger a publish to test if all changes produce a valid, publishable java implementation of the specification
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx16384m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'publish'

- job: successNotification
  dependsOn: publish
  condition: succeeded()
  timeoutInMinutes: 5
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        SVNREV=$(git rev-parse --short HEAD)
        LASTMSG=$(git log --oneline --graph HEAD~1..)
        
        curl -X POST https://chat.fhir.org/api/v1/messages \
            -u $(ZULIP_BOT_EMAIL):$(ZULIP_BOT_API_KEY) \
            -d "type=stream" \
            -d "to=$(ZULIP_STREAM_ID_COMMITTERS)" \
            -d "subject=FHIR Build Status" \
            -d $"content=Build success :thumbs_up:! @${SVNREV} [build logs](https://dev.azure.com/fhir-pipelines/fhir-publisher/_build/results?buildId=${BUILD_BUILDNUMBER}&_a=summary&view=logs)
        \`\`\`
        ${LASTMSG}
        \`\`\`
        "

- job: failureNotification
  dependsOn: publish
  condition: failed()
  timeoutInMinutes: 5
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        SVNREV=$(git rev-parse --short HEAD)
        FAIL_MSG=$(cat publish/simple-error.txt)
        
        curl -X POST https://chat.fhir.org/api/v1/messages \
            -u $(ZULIP_BOT_EMAIL):$(ZULIP_BOT_API_KEY) \
            -d "type=stream" \
            -d "to=$(ZULIP_STREAM_ID_COMMITTERS)" \
            -d "subject=FHIR Build Status" \
            -d $"content=Build failed :thumbs_down:! @${SVNREV} [build logs](https://dev.azure.com/fhir-pipelines/fhir-publisher/_build/results?buildId=${BUILD_BUILDNUMBER}&_a=summary&view=logs)
        \`\`\`
        ${FAIL_MSG}
        \`\`\`
        "
