# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pr:
- master

jobs:
- job: buildSpecification
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "1. source branch -> $(Build.SourceBranch)"
        echo "2. source branch -> $(Build.SourceBranchName)"
        echo "3. source branch -> $(System.PullRequest.SourceBranch)"
        echo "2. source branch -> $(System.PullRequest.TargetBranch)"
